### ISSUE TITLE
Fix API import issue when trying to run the `api.py` file

### ISSUE THREAD

**Issue by life-efficient** [life-efficient/Parapet-Workbench#4]
This is probably an error I introduced whilst disentangling everything. It probably just requires you to change the import statement.

Current error: `ImportError: cannot import name 'voice_to_text' from 'workbench.transcriber' (/Users/ice/lectures/workbench/workbench/transcriber.py)`

How to reproduce:
1. Run the `examples/web_voice_chat/api.py` file

**Comment by abrantesfg** [comment]
Manage to fix here. Solved in a slightly different way, less lines of code :)

Using now

`main_dir = os.getcwd().split("examples")[0]
sys.path.append(main_dir) `
