### ISSUE TITLE
Create shareable env to allow easy installation

### ISSUE THREAD

**Issue by life-efficient** [life-efficient/Parapet-Workbench#9]
Create a conda environment that can be installed by any new joiner to the project.

**Comment by Halzorg** [comment]
I would like to work on this issue, could you please assign it to me?

**Comment by nisartahir** [comment]
Current work for this is in: https://github.com/life-efficient/Parapet-Workbench/tree/imports

**Comment by nisartahir** [comment]
> I would like to work on this issue, could you please assign it to me?

I have added you Hazim
